language: go

os:
  - linux
  - osx

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - tip

before_install:
  - if [[ $TRAVIS_GO_VERSION == 1.10* ]]; then go get github.com/axw/gocov/gocov github.com/mattn/goveralls; fi

script:
  - go test -v -tags ci ./...
  - if [[ $TRAVIS_GO_VERSION == 1.10* ]]; then $GOPATH/bin/goveralls -service=travis-ci -ignore="examples/generator/main.go,examples/simple/main.go"; fi

notifications:
  email:
    on_success: change
    on_failure: always
